server:
  port: 8002  servlet:    context-path: /user
spring:  application:    name: jt-user  datasource:
   # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///market?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root  http:    encoding:      force-response: true
  redis:
    host: 192.168.40.152
    port: 6379 
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
mybatis:  mapper-locations: classpath:/mapper/*.xml
  configuration:    map-underscore-to-camel-case: true    default-scripting-language: 
page:
  size: 5
#打开降级熔断
feign:
  hystrix:
    enabled: true
#hystrix超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500


##配置ribbon超时
ribbon:
  ReadTimeOut: 500
  ConnectTimeout: 500
  
  
#暴露监控断点，供hystrix仪表盘监控健康状态  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  instanceUrlSuffix: /hystrix.stream
